### ISSUE TITLE
api_id越界，超过long表示类型

### ISSUE THREAD

**Issue by enbiwudi** [holll/teledown#24]
api_id越界，超过long表示类型，报错如下
`File "C:\Users\lujd\miniconda3\Lib\site-packages\telethon\tl\functions\__init__.py", line 127, in _bytes
    struct.pack('<i', self.api_id)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647`

修改<i为<q后

`File "C:\Users\lujd\miniconda3\Lib\site-packages\telethon\client\telegrambaseclient.py", line 541, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: INPUT_METHOD_INVALID_7234818_2151521 (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))`

请问如何解决呢

**Comment by holll** [comment]
这个你要去找框架作者反馈了，是telethon抛出的报错
